:toc: left
:source-highlighter: pygments
:doctype: book
:idprefix:
:docinfo:
:listing-caption: "Example: "
# Concepts

## Logical services and backends

Many parts of `cueball` deal with the concept of a "logical service". This is
a uniquely named entity (usually a DNS name) that is used to refer to a
service offered to the network by potentially many processes running on many
machines.

For example, `(_dns._udp.)binder.staging-1.joyent.us` is a logical service that
provides DNS (over UDP), under the unique name `binder.staging-1.joyent.us`.
There may be only one physical machine providing this logical service, or there
may be many, and on each physical machine there may be multiple processes
providing it, or just one.

Each process on each machine that provides the service is referred to as a
"backend" for that logical service. A backend is uniquely identified within
a given logical service by the tuple of network (IP) `address` and `port`.

Note that for a group of backends to be part of the same logical service, it
should be completely equivalent to connect to one of them as any other (i.e.
there must be no requirement from the application to connect to some specific
individual backend at any time).

## Resolvers

A "resolver" is the name we give to a component responsible for locating all of
the backends available within a logical service, obtaining their IP address and
port information (or whatever is required to connect to them) and tracking them.
This is normally a service discovery client of some form -- e.g. `cueball`
provides a default DNS-based Resolver which uses DNS SRV records as a form of
service discovery mechanism to find backends.

You can plug your own Resolver implementation into `cueball` to provide this
mechanism, however, as long as it can track changes in the set of backends in a
timely manner (it is expected to emit events only on changes, rather than
periodic polling or refreshes).

## Connections

In `cueball`, a "connection" is not necessarily just a TCP socket. It can be
any EventEmitter that provides some kind of logical connection to a given
backend, as long as it obeys a similar interface to a socket.

This is intended to allow users of the API to represent a "connection" as an
application or session layer concept. For example, it could be useful to
construct a pool of connections to an LDAP server that perform a bind
operation (authenticate) before they are considered "connected".

The user of the `cueball` API passes in a "constructor" function which, when
called, must return a new connection object that has begun an attempt to
connect. More details about this are included further into the API
documentation.

## Connection pools and sets

The principal active components of `cueball` are connection Pools, and Sets.

A connection Pool is a set of connections maintained to any subset of available
backends for one single logical service. The connections are handed out to users
of the pool in a temporary lease, then later returned to the pool for re-use.
A single connection is never given out concurrently to more than one user of
the pool. This paradigm is ideal for many common protocols such as HTTP, LDAP,
database connections etc.

A connection Set is the same concept as a connection Pool, but with the ability
for a single connection to be used by more than one user at the same time. It
is designed for use with services that multiplex operations onto a single socket
or which are not as strictly connection-oriented and ordered.

## Further information

More detailed exploration of these concepts and the design of `cueball` can be
found in the link:./internals.html[Cueball internals] document.

# API
:sectnums:

[[agent]]
## HttpAgent, HttpsAgent

### `new HttpAgent(options)`
### `new HttpsAgent(options)`

Creates an HTTP(S) agent that can be used with the node `http` client API. The
agent implicitly creates a ConnectionPool for each new hostname it encounters
when processing requests.

You can either pre-populate the set of pools by giving the `initialDomains`
option, or simply make requests and the pools will be constructed at the first
request for each host.

Parameters

- `options` -- Object, with keys:
  * `recovery` -- Object, a recovery spec (see below)
  * `spares` -- Number, number of spares wanted in the pool per host
  * `maximum` -- Number, maximum number of connections per host
  * `resolvers` -- optional Array of String, either containing IP addresses to
    use as nameservers, or a single string for Dynamic Resolver mode
  * `log` -- optional Object, a `bunyan`-style logger to use
  * `initialDomains` -- optional Array of String, initial domains to create
    connections to at startup (to pre-seed the Agent for quick use later)
  * `defaultPort` -- optional Number, fallback TCP port to connect to (default
    80 for HttpAgent, 443 for HttpsAgent). If SRV records for a name are found
    the port from SRV will always be used instead of this.
  * `tcpKeepAliveInitialDelay` -- optional Number, if supplied, enable TCP
    level keep-alives with the given initial delay (in milliseconds)
  * `ping` -- optional String, URL path to use for health checking. Connection
    is considered still viable if this URL returns a non-5xx response code.
  * `pingInterval` -- optional Number, interval between health check pings
  * `errorOnEmpty` -- optional Boolean

### `#stop([cb])`

Stops the pools managed by this agent, calling `cb` (if given) once all have
stopped.

Once an Agent has been stopped, it can no longer accept any new requests, and
will throw an Error if asked to do so. Calling `stop()` more than once is
also an error and will throw.

Parameters

- `cb` -- optional Function (err)

NOTE: Any pools spun up by the Agent will continue to keep the process
open even if there are no outstanding requests (due to the spare connections
held by the pool). The `stop()` method should be used on an Agent if your
program does not plan to use it again and wishes to be able to exit node
without calling `process.exit()`.

### `#getPool([host])`

Returns the connection pool this agent has created for the input host. If no
pool has yet been created, returns `undefined`.

Parameters

- `host` -- String, hostname of the host for which the pool is being requested.

### `#createPool(host, [options])`

Creates and returns a connection pool for the host identified by the input host
name if one doesn't already exist. You can either provide a resolver directly in
the options parameter or have one allocated by cueball (the behaviour matches
`resolverForIpOrDomain()`). If you provide a resolver, the Agent takes no
responsibility for calling its `start()` or `stop()` methods. The caller is
responsible for doing so.

Parameters

- `host` -- String, hostname of the host for which a pool will be created.
- `options` -- an optional Object, with keys:
    * `resolver` -- optional Object satisfying the Resolver interface, the
                    resolver to use for this pool. If given, `port` will be
                    ignored.
    * `port` -- optional Number, override the default port number used for
                this pool (the Resolver can still override this).
    * `rejectUnauthorized`, `pfx`, `key`, `passphrase`, `cert`, `ca`, `ciphers`,
      `servername` -- TLS options, passed through to the TLS library.

NOTE: This function throws an error synchronously if a resolver for the
provided host already exists, or if the Agent is stopped.

[[pool]]
## ConnectionPool

### State transitions

ConnectionPool exposes the `mooremachine` FSM interface, with the following
state graph:

.ConnectionPool state transition diagram
-----------------------------------------------------------------------------
                                                           | (from failed)
                                                .stop()    v
             +--------+   connect ok   +-------+       +--------+
    init --> |starting| +------------> |running| +---> |stopping|
             +--------+                +-------+       +--------+
                 +                      ^     +            +
        resolver |                      |     |            |
          failed |                      |     |            |
              OR |       +------+       |     |            v
         retries +---->  |failed| +-----+     |        +-------+
       exhausted         +------+ connect ok  |        |stopped|
                          +  ^                |        +-------+
                          |  |                |
                   .stop()|  +----------------+
                          |   all retries exhausted
-----------------------------------------------------------------------------

Pools begin their life in the "starting" state. Once they have successfully made
one connection to any backend, they proceed to the "running" state. Otherwise,
if their underlying Resolver enters the "failed" state, or they exhaust their
retry policy attempting to connect to all their backends, they enter the
"failed" state. Here they keep trying to connect to valid backends at their
maximum backoff values, so as to be able to detect if a backend recovers.

A "running" pool can then either be stopped by calling the `.stop()` method, at
which point it enters the "stopping" state and begins tearing down its
connections; or all of its connections become disconnected and it exhausts its
retry policy, in which case it enters the "failed" state.

Failed pools can re-enter the "running" state at any time if they make a
successful connection to a backend and their underlying Resolver is no longer
"failed". A "failed" pool can also have the `.stop()` method called, in which
case it proceeds much as from "running".

[[new-pool, ConnectionPool]]
### `new ConnectionPool(options)`

Creates a new pool of connections.  There are two ways of using a
ConnectionPool.  You can either provide your own resolver directly, or provide
parameters with which to create the default, DNS-based resolver.

Parameters

- `options` -- Object, with keys:
  * `constructor` -- Function(backend) -> object, must open a new connection
    to the given backend and return it
  * `domain` -- String, name to look up to find backends.
  * `recovery` -- Object, a recovery spec (see below)
  * `spares` -- Number, number of spares wanted in the pool per host
  * `maximum` -- Number, maximum number of connections per host
  * `service` -- optional String, name of SRV service (e.g. `_http._tcp`)
  * `defaultPort` -- optional Number, port to use for plain A/AAAA records
  * `resolvers` -- optional Array of String, either containing IP addresses to
    use as nameservers, or a single string for Dynamic Resolver mode (default
    uses system resolvers from `/etc/resolv.conf`)
  * `log` -- optional Object, a `bunyan`-style logger to use
  * `maxDNSConcurrency` -- optional Number, max number of DNS queries to issue
    at once (default 5)
  * `checkTimeout` -- optional Number, milliseconds of idle time before
    running `checker` on a connection
  * `checker` -- optional Function(handle, connection), to be run on idle
    connections
  * `targetClaimDelay` -- optional Number, a target time for latency to claim
    accept/timeout, done through Adaptive Queue Management
  * `resolver` -- optional instance of an object meeting the Resolver interface
    below.  You would typically obtain this object by either creating your own
    Resolver directly or using the `resolverForIpOrDomain` function.

Do not confuse `resolvers` (the list of IP addresses for the DNS resolvers to
contact) with `resolver` (a custom object meeting the Resolver interface below).

If you want to use a custom resolver, then you must specify the `resolver`
property.  In that case, the `resolvers`, `maxDNSConcurrency`, `defaultPort`,
and `recovery` options are ignored, and the `domain` and `service` properties
are used only for logging.

Otherwise, if want to use the default DNS-based resolver, do not specify the
`resolver` property.  A resolver instance will be created based on the other
configuration properties.

### `#stop()`

Stops the connection pool and its `Resolver`, then destroys all connections.

NOTE: Any pool running in a process will continue to keep the process
open even if there are no outstanding claims or activity (due to the spare
connections held by the pool). The `stop()` method is the correct way to
allow the process to exit if there is no more work to be done using the Pool.

### `#claim([options, ]callback)`

Claims a connection from the pool ready for use.

Parameters

- `options` -- optional Object, with keys:
  * `timeout` -- optional Number, timeout for request in ms
    (default `Infinity`)
  * `errorOnEmpty` -- optional Boolean, if true return error straight away
    if the pool has no backends at all (i.e., nothing was found in DNS)
- `callback` -- Function(err[, handle, connection]), parameters:
  * `err` -- an Error object, if the request could not be fulfilled or timed
    out
  * `handle` -- Object, handle to be used to release the connection back to
    the pool when work is complete
  * `connection` -- Object, the actual connection (as returned by the
    `constructor` given to `new ConnectionPool()`)

Returns a "waiter handle", which is an Object having a `cancel()` method. The
`cancel()` method may be called at any time up to when the `callback` is run, to
cancel the request to the pool and relinquish any queue positions held.

When a client is done with a connection, they must call `handle.release()` to
return it to the pool. All event handlers should be disconnected from the
`connection` prior to calling `release()`.

If a client determines that a connection must be closed immediately (e.g. due
to a protocol error making it impossible to continue using it safely), it must
call the `.close()` method on the *handle*, not any `.destroy()` or similar
method on the connection itself.

Calling `claim()` on a Pool that is in the "stopping", "stopped" or "failed"
states will result in the callback being called with an error on the next run of
the event loop.

NOTE: The `connection` object given to you in the callback for `claim()` may
emit `'error'`. If you do not register a handler for this event immediately
at the start of your claim, and it emits, this will be treated as an uncaught
error and cause the program to crash.

### `#getLastError()`

When the pool has entered state "failed", this method may be used to retrieve
the last Error object emitted by a connection attempt in the pool. Note that
while this is very likely to be a proximate cause of the pool failure,
determining the root cause may require further analysis.

Returns an Error object.

### `#getStats()`

Returns an object containing a snapshot of the current counters, along with
with four additional numbers: total connections, idle connections, partly-open
connections, and the number of requests queued waiting.

.An object returned by #getStats()
[source,js,caption="Example: "]
-----------------------------------------------------------------------------
{ counters:
   { claim: 1,
     'max-claim-queue': 1,
     'queued-claim': 1 },
  totalConnections: 1,
  idleConnections: 1,
  pendingConnections: 0,
  waiterCount: 0
}
-----------------------------------------------------------------------------

## Resolver

### About the interface

An interface for all "resolvers", objects which take in some kind of
configuration (e.g. a DNS name) and track a list of "backends" for that
name. A "backend" is an IP/port pair that describes an endpoint that can
be connected to to reach a given service.

Resolver exposes the `mooremachine` FSM interface, with the following state
graph:

                    .start()          error
            +-------+       +--------+       +------+
    init -> |stopped| +---> |starting| +---> |failed|
            +---+---+       +---+----+       +------+
                ^               |               +
                |               | ok            |
                |               v               |
            +---+----+      +---+---+           |
            |stopping| <--+ |running|  <--------+
            +--------+      +-------+       retry success
                     .stop()

Resolvers begin their life "stopped". When the user calls `.start()`, they
begin the process of resolving the name/configuration they were given into
backends.

If the initial attempt to resolve the name/configuration fails, the Resolver
enters the "failed" state, but continues retrying. If it succeeds, or if any
later retry succeeds, it moves to the "running" state. The reason why the
"failed" state exists is so that commandline tools and other short-lived
processes can make use of it to decide when to "give up" on a name resolution.

Once an attempt has succeeded, the Resolver will begin emitting `added` and
`removed` events (see below) describing the backends that it has found.

In the "running" state, the Resolver continues to monitor the source of its
backends (e.g. in DNS by retrying once the TTL expires) and emitting these
events when changes occur.

Finally, when the `.stop()` method is called, the Resolver transitions to
"stopping", stops monitoring and emitting events, and comes to rest in the
"stopped" state where it started.

### `#start()`

Starts the resolver's normal operation (by beginning the process of looking up
the names given).

### `#stop()`

Stops the resolver. No further events will be emitted unless `start()` is
called again.

### `#getLastError()`

Returns the last error experienced by the Resolver. This is particularly useful
when the Resolver is in the "failed" state, to produce a log message or user
interface text.

### `#getState()`

Returns the current state of the Resolver as a string (see diagram above).

Inherited from `mooremachine.FSM`.

### `#isInState(state)`

Returns true if `state` matches the current state of the Resolver
(see diagram above).

Inherited from `mooremachine.FSM`.

### `->stateChanged(state)`

An event that fires whenever the Resolver changes state.

Inherited from `mooremachine.FSM`.

### `->added(key, backend)`

Emitted when a new backend has been found.

Parameters

 - `key` -- String, a unique key for this backend (will be referenced by any
   subsequent events about this backend)
 - `backend` -- Object, with keys:
   * `name` -- String, the DNS name for this backend
   * `address` -- String, an IPv4 or IPv6 address
   * `port` -- Number

### `->removed(key)`

Emitted when an existing backend has been removed.

Parameters

 - `key` -- String, unique key for this backend

## DNS-based name resolver

### `new DNSResolver(options)`

Creates a Resolver that looks up a name in DNS. This Resolver prefers SRV
records if they are available, and falls back to A/AAAA records if they cannot
be found.

Parameters

- `options` -- Object, with keys:
  * `domain` -- String, name to look up to find backends
  * `recovery` -- Object, a recovery spec (see below)
  * `service` -- optional String, name of SRV service (e.g. `_http._tcp`)
  * `defaultPort` -- optional Number, port to use for plain A/AAAA records
  * `resolvers` -- optional Array of String, either containing IP addresses to
    use as nameservers, or a single string for Dynamic Resolver mode (default
    uses system resolvers from `/etc/resolv.conf`)
  * `log` -- optional Object, a `bunyan`-style logger to use
  * `maxDNSConcurrency` -- optional Number, max number of DNS queries to issue
    at once (default 5)

## Static IP resolver

### `new StaticIpResolver(options)`

Creates a new static IP resolver.  This object matches the Resolver interface
above, but emits a fixed list of IP addresses when started.  This list never
changes.  This is intended for development environments and debugging tools,
where a user may have provided an explicit IP address rather than a DNS name to
contact.  See also: `resolverForIpOrDomain()`.

Parameters

- `options` -- Object, with keys:
  * `defaultPort` -- optional Number, fallback port to use for backends
    that only have an `address` property
  * `backends` -- Array of objects, each having properties:
    ** `address` -- String, an IP address to emit as a backend
    ** `port` -- Number (optional if `defaultPort` used), a port number
        for this backend

This object provides the same `start()` and `stop()` methods as the Resolver
class, as well as the same `added` and `removed` events.



## Picking the right resolver

### `resolverForIpOrDomain(options)`

Services that use DNS for service discovery would typically use a DNS-based
resolver.  But in development environments or with debugging tools, it's useful
to be able to point a cueball-using program at an instance located at a specific
IP address and port.  That's what the Static IP resolver is for.

To make this easy for programs that want to support connecting to either
hostnames or IP addresses, this function is provided to take a configuration
(expected to come from a user, via an environment variable, command-line
option, or other configuration source), determine whether an IP address or DNS
name was specified, and return either a DNS-based or static resolver.  If the
input appears to be neither a valid IPv4 nor IPv6 address nor DNS name, or the
port number is not valid, then an Error is returned (not thrown).  (If the
input is missing or has the wrong type, an Error object is thrown, since this
is a programmer error.)

Parameters

- `options` -- Object, with keys:
  * `input` -- String, either an IP address or DNS name, with optional port
    suffix
  * `resolverConfig` -- Object, a set of additional properties to pass to
    the resolver constructor, with keys:
    ** `defaultPort` -- optional Number, used for both DNS and static names
    ** `recovery` -- Object, see `DNSResolver`, required for DNS lookups
    ** `service` -- optional String, see `DNSResolver`
    ** `resolvers` -- optional Array of String, see `DNSResolver`
    ** `log` -- optional Object, a `bunyan`-style logger to use

The `input` string has the form `HOSTNAME[:PORT]`, where the `[:PORT]` suffix is
optional, and `HOSTNAME` may be either an IP address or DNS name.

.Creating a resolver that will emit one backend for an instance at IP 127.0.0.1 port 2020
[source,js,caption="Example: "]
-----------------------------------------------------------------------------
var resolver = mod_cueball.resolverForIpOrDomain({
    'input': '127.0.0.1:2020',
    'resolverConfig': {
        'recovery': {
            'default': {
                'retries': 1,
                'timeout': 1000,
                'delay': 1000,
                'maxDelay': 1000
            }
        }
    }
})
/* check whether resolver is an Error */
-----------------------------------------------------------------------------

.Creating a resolver that will track instances associated with DNS name `mydomain.example.com`
[source,js,caption="Example: "]
-----------------------------------------------------------------------------
var resolver = mod_cueball.resolverForIpOrDomain({
    'input': 'mydomain.example.com',
    'resolverConfig': {
        'recovery': {
            'default': {
                'retries': 1,
                'timeout': 1000,
                'delay': 1000,
                'maxDelay': 1000
            }
        }
    }
});
/* check whether resolver is an Error */
-----------------------------------------------------------------------------

In these examples, the `input` string is assumed to come from a user
cueball does the expected thing when given an IP address or DNS name.

### `DNSResolver.getBootstrapResolver([host])`

Returns the `DNSResolver` created for the input host when
`resolverForIpOrDomain` is used to create a bootstrap resolver, i.e. a
resolver for the DNS service itself. If no resolver has yet been created,
returns `undefined`.

Parameters

- `host` -- String, hostname of the host for which the resolver is being
requested.

## Connection interface

Objects returned by a `constructor` function (such as supplied to the
`ConnectionPool` constructor) must obey a subset of the node.js socket
interface. In particular they must support the following events and methods:

### `constructor(backend)`

Parameters

 - `backend` -- an Object, with properties:
   - `key` -- a String, the backend key as supplied via the Resolver interface.
              Can be used to uniquely identify the backend.
   - `address` -- a String, address of the backend (IPv4 or IPv6)
   - `port` -- a Number, TCP or UDP port number

Returns an object obeying the Connection interface.

### `->connect()` (required)

At construction, the connection object must immediately attempt to make a
connection to the backend specified by the first argument to the constructor.
When the connection succeeds, it must emit the event `connect`. No arguments are
required.

### `->close()` (required)

Connection objects must emit `close` as the final event they emit after the
connection has ended. No events may be emitted after `close`.

### `#destroy()` (required)

Immediately disconnects the connection and proceeds to emit `close`.

### `->error(errObj)`

Connection objects may emit `error` at any time in response to a fatal error.
The connection will be immediately terminated (by calling `.destroy()`) upon the
emission of any `error` event.

The `error` event should be emitted with an Object as the first parameter. This
is expected to have `Error` on its prototype chain (`obj instanceof Error`
should be `true`).

May also be emitted as `connectError` only in the state before `connect` has
been emitted.

### `->timeout()`

Optional. Equivalent to emitting `error` with a ConnectionTimeoutError as an
argument.

May also be emitted as `connectTimeout` only in the state before `connect` has
been emitted.



## Errors

### `ClaimTimeoutError`

Passed as first argument to `ConnectionPool#claim()`'s callback when the given
timeout in `options` has been exceeded.

Properties

 - `pool` -- ConnectionPool

### `NoBackendsError`

Passed as first argument to `ConnectionPool#claim()`'s callback when there are
no known backends for the pool and the `errorOnEmpty` flag is set.

Properties

 - `pool` -- ConnectionPool



## Kang support

### `poolMonitor.toKangOptions()`

Returns an options object that can be passed to `mod_kang.knStartServer`. The
kang options set up snapshots containing a list of all `Pool` objects in the
system and their associated backends and state.

The returned object is missing the `port` property, which should be added
before using.

## Recovery objects

To specify the retry and timeout behaviour of Cueball DNS and pooled
connections, the "recovery spec object" is a required argument to most
constructors in the API.

A recovery spec object should always have at least one key, named `"default"`,
which gives the default settings for any operation.

More specific per-operation settings can also be given as additional keys.

.A simple recovery object
[source,js,caption="Example: "]
-----------------------------------------------------------------------------
{
  default: {
    timeout: 2000,
    retries: 3,
    delay: 100
  },
  dns: {
    timeout: 5000,
    retries: 3,
    delay: 200
  }
}
-----------------------------------------------------------------------------

This specifies that DNS-related operations should have a timeout of 5 seconds,
3 retries, and an initial delay of 200ms, while all other operations (e.g.
`connect()` while connecting to a new backend) should have a timeout of 2
seconds, 3 retries and initial delay of 100ms.

The `delay` field indicates a time to wait between retry attempts. After each
failure, it will be doubled until it exceeds the value of `maxDelay`.

It is important to note that running out of `retries` does not cause an
`'error`' event or thrown exception. Due to cueball's "monitor" behaviour, there
is no real limit generally on the total number of times it will attempt to
connect to a given backend. The `retries` value is used to know when to stop
increasing backoff exponentially, when to declare a backend "dead", and when to
declare a pool "failed", but none of these will cause cueball to stop attempts
to reconnect to the backend unless you act to change it. The
link:./internals.html[Cueball internals] document explains this in more detail.

The possible fields in one operation are:

 - `retries` -- finite Number >= 0, number of retry attempts
 - `timeout` -- finite Number > 0, milliseconds to wait before declaring an
   attempt a failure
 - `maxTimeout` -- Number > `timeout` (can be `Infinity`), maximum value of
   `timeout` to be reached with exponential timeout increase
 - `delay` -- finite Number >= 0, milliseconds to delay between retry attempts
 - `maxDelay` -- Number > `delay` (can be `Infinity`), maximum value of `delay`
   to be reached with exponential delay increase

And the available operations:

 - `dns` -- all DNS-related operations, lookups etc
 - `dns_srv` -- specifically lookups on SRV records, this is separate in case
   you need to deal with certain old buggy DNS servers that have trouble with
   SRV)
 - `connect` -- connections to backends in a `ConnectionPool`
 - `initial` -- the very first attempt to connect to a new backend, will fall
   back to `connect` if not given

If a given operation has no specification given, it will use `default` instead.


## Dynamic Resolver mode

`Resolver` instances can operate in a so-called "Dynamic Resolver" mode, where
as well as tracking their particular target service in DNS, they also track the
correct nameservers to ask about it.

This is useful in systems where the nameservers are listed in DNS as a service
just like your ordinary target service (e.g. HTTP). An example is the Joyent
SDC `binder`. `binder` acts as a DNS server, listing addresses of all SDC
service instances. This includes listing its own address, and if multiple
`binder`s are deployed, all other `binder`s in the DC.

We can look up the list of currently available `binder` instances in DNS, and
use this to perform our name resolution. We can also then use the `binder`s to
update our original list of `binder` instances.

This mode requires a "bootstrap" to begin with, however -- we cannot resolve
the name that the `binder` instances are listed under until we already know the
address of one of the `binder`s. In Dynamic Resolver mode, `cueball` will
bootstrap using the system resolvers from `/etc/resolv.conf`.

### Example

.Using dynamic resolver mode
[source,js,caption="Example: "]
-----------------------------------------------------------------------------
const mod_cueball = require('cueball');
const mod_restify = require('restify-clients');

var client = mod_restify.createJsonClient({
    url: 'http://napi.coal.joyent.us',
    agent: new mod_cueball.HttpAgent({
        resolvers: ['binder.coal.joyent.us'],
        spares: 4, maximum: 8
    })
});

client.get('/networks/' + uuid, function (err, req, res, data) {
    ...
});
-----------------------------------------------------------------------------

This example code will start by using the system resolvers to resolve
`binder.coal.joyent.us`. Then, the records found via this lookup will be used
as nameservers to look up `napi.coal.joyent.us`.

When the TTL expires on the records for `binder.coal.joyent.us`, we will use
the records from the previous lookup as the list of nameservers to query in
order to find out what the new records should be. Then, we will use any new
nameservers we find for the next `napi.coal.joyent.us` lookup as well.



## ConnectionSet

Cueball also includes an alternative to the ConnectionPool, named ConnectionSet.
This is a more low-level API which is useful for implementing clients for
protocols that are not as strictly connection-oriented.

Key differences to ConnectionPool:

 - Each backend in a ConnectionSet has a maximum of 1 connection open to it
   (it's expected to be used with protocols that multiplex operations over a
   single socket.)
 - No support for leases (claim/release). ConnectionSet does not track whether
   connections are busy or not, and expects its consumer to manage this.

Note that neither ConnectionSet nor ConnectionPool are suited or designed for
use with sets of distinct backends that are not for a single logical service.
All of the backends returned by your resolver should always be equivalent and
interchangeable, no matter which interface you use.

The only reason you should be using a ConnectionSet is if you really wanted a
ConnectionPool, but your service multiplexes operations over a single socket
or isn't strictly connection-oriented.

ConnectionSets have an identical state graph to ConnectionPools.

### `new ConnectionSet(options)`

Parameters

 - `options` -- Object, with keys:
   * `resolver` -- Object, an instance of the Resolver interface
   * `constructor` -- Function, same as in ConnectionPool
   * `recovery` -- Object, a recovery spec (see below)
   * `target` -- Number, target number of connections to be made
                 available in the entire set
   * `maximum` -- Number, maximum number of sockets opened by the set.
                  Note that this number may temporarily be exceeded by 1 socket
                  to allow the set to re-balance.
   * `log` -- optional Object, a `bunyan`-style logger to use
   * `connectionHandlesError` -- optional Boolean (default `false`). If `true`,
                                 cueball assumes that the connection object (the
                                 instance returned from `constructor`) handles
                                 `"error"` events internally and the emission of
                                 this event is for cueball's information only.

### `->added(key, connection, handle)`

Emitted when a new connection becomes available in the set. This event *must*
have a handler on it at all times.

The `handle` that is given as the third argument to this event has two methods
`.release()` and `.close()`, like a Pool handle. As with Pool handles, the
`.close()` method can be used to indicate an otherwise undetectable failure of a
connection (e.g. due to a protocol error making safe use of the connection
impossible) at any time, but unlike a Pool handle, it is an error to call
`.release()` until after a `'removed'` event has been emitted.

The user of the ConnectionSet should store both the `connection` and `handle`
in such a way as to be able to retrieve them using the `key` (so they can
handle any related `'removed'` event later).

If the `.close()` method is called on a Set handle, no `'removed'` event will
be emitted about this connection. It is the caller's responsibility to clean
up any remaining state on its side.

Parameters

 - `key` -- String, a unique key to identify this connection
 - `connection` -- Object, the connection as returned by the constructor
 - `handle` -- Object, a handle to be used in response to a 'removed' event
   about this connection

WARNING: Failing to add a handler to this event *will* cause your program to
crash.

### `->removed(key)`

Emitted when an existing connection should be removed from the pool. This event
*must* have a handler on it at all times. The handler is obligated to take all
necessary actions to drain the connection of outstanding requests and then
call the `.release()` method on the relevant handle.

Parameters

 - `key` -- String, a unique key to identify the connection

WARNING: Failing to add a handler to this event *will* cause your program to
crash.

### `#stop()`

Stops the ConnectionSet, disconnecting all available connections (by first
emitting `'removed'` for them.)

### `#setTarget(target)`

Sets the target number of connections in the ConnectionSet. Will trigger an
async operation to add or remove connections in order to meet the new target.

Parameters

 - `target` -- Number

### `#getConnections()`

Returns all the currently open connections in the Set, as an Array.

### `#getLastError()`

When the set has entered state "failed", this method may be used to retrieve
the last Error object emitted by a connection attempt for the set. Note that
while this is very likely to be a proximate cause of the failure,
determining the root cause may require further analysis.

Returns an Error object.

# Tools

## cbresolve

The `cbresolve` tool is provided to show how cueball would resolve a given
configuration.  The output format is not committed.  It may change in the
future.

.Commandline help for the `cbresolve` command
-----------------------------------------------------------------------------
usage: cbresolve HOSTNAME[:PORT]                # for DNS-based lookup
       cbresolve -S | --static IP[:PORT]...     # for static IPs
Locate services in DNS using Cueball resolver.

The following options are available for DNS-based lookups:

    -f, --follow                periodically re-resolve and report changes
    -p, --port PORT             default backend port
    -r, --resolvers IP[,IP...]  list of DNS resolvers
    -s, --service SERVICE       "service" name (for SRV)
    -t, --timeout TIMEOUT       timeout for lookups
-----------------------------------------------------------------------------

.Using `cbresolve` to resolve the DNS name `1.moray.us-east.joyent.us`
[caption="Example: "]
-----------------------------------------------------------------------------
$ cbresolve 1.moray.emy-10.joyent.us
domain: 1.moray.emy-10.joyent.us
timeout: 5000 milliseconds
172.27.10.218       80 lLbminikNKjfy+iwDobYBuod7Hs=
172.27.10.219       80 iJMaVRehJ2zKfiS55H/lUUFPb9o=
-----------------------------------------------------------------------------

.Using `cbresolve` to resolve IP/port "127.0.0.1:2020"
[caption="Example: "]
-----------------------------------------------------------------------------
$ cbresolve --static 127.0.0.1:2020
using static IP resolver
127.0.0.1         2020 xBut/f1D52k1TpDN/miW82qXw6k=
-----------------------------------------------------------------------------

[[watch-example]]
.Using `cbresolve` to resolve a name and watch for changes
[caption="Example: "]
-----------------------------------------------------------------------------
$ cbresolve --follow 1.moray.emy-10.joyent.us
domain: 1.moray.emy-10.joyent.us
timeout: 5000 milliseconds
2016-06-23T00:45:00.312Z added      172.27.10.218:80    (lLbminikNKjfy+iwDobYBuod7Hs=)
2016-06-23T00:45:00.314Z added      172.27.10.219:80    (iJMaVRehJ2zKfiS55H/lUUFPb9o=)
2016-06-23T00:49:00.478Z removed    172.27.10.218:80    (lLbminikNKjfy+iwDobYBuod7Hs=)
-----------------------------------------------------------------------------

In the <<watch-example,last example>>, one of the DNS entries was removed a few
minutes after the program was started.
